[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 30

[nixpacks]
version = "1.21.2"

[nixpacks.phases.setup]
nixPkgs = ["nodejs-20_x"]
